version: '3.8'

networks:
  odoo-db-network:
    driver: bridge

services:
  pg-0: 
    image: bitnami/postgresql-repmgr:latest
    ports:
      - 5432
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=your-pwd
      - POSTGRESQL_USERNAME=odoo
      - POSTGRESQL_PASSWORD=your-pwd
      - POSTGRESQL_DATABASE=odoo_db
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=your-pwd
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    volumes:
      - pg_0_data:/bitnami/postgresql
    networks: 
      - odoo-db-network

  pg-1:
    image: bitnami/postgresql-repmgr:latest
    ports:
      - 5432
    environment: 
      - POSTGRESQL_POSTGRES_PASSWORD=your-pwd
      - POSTGRESQL_USERNAME=odoo
      - POSTGRESQL_PASSWORD=your-pwd
      - POSTGRESQL_DATABASE=odoo_db
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=your-pwd
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    volumes:
      - pg_1_data:/bitnami/postgresql
    networks: 
      - odoo-db-network
    
  pgpool:
    image: bitnami/pgpool:latest
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432;1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=repmgr
      - PGPOOL_SR_CHECK_PASSWORD=your-pwd
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=odoo
      - PGPOOL_POSTGRES_PASSWORD=your-pwd
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=your-pwd
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - odoo-db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "your-mail@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "your-pwd"
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
    ports:
      - 5050:80
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: 
      - odoo-db-network

volumes:
  pg_0_data:
  pg_1_data:
  pgadmin4-data:
